apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}
    spec:
      containers:
        - name: {{ .Values.nameOverride }}
          imagePullPolicy: Always
          image: "{{ .Values.reactClient.image }}:{{ .Values.reactClient.imageTag }}"
          ports:
            - containerPort: {{ .Values.reactClient.port }}
